### ISSUE TITLE
Crash: Scanning Obsidian Tiles

### ISSUE THREAD

**Issue by ShyGuyMD** [wyldmods/WyldCraftIssues#11]
Tried scanning (with a Thaumometer) the topmost part of an Obsidian Totem (the Obsidian Tile) that had no node, and it crashed.

Crash Log:
http://pastebin.com/04sSAagg

**Comment by Mandabar** [comment]
Hmm... Same issue. One scanned one so far. 
http://paste.ee/p/qCNQm
Wasn't issue in Alpha.though.
Location was 120, 1797 I believe... Though after login. nothing here. No pillar at all now. It had no node. Perhaps the shy guy saw.
It did indeed have no node. Other ones scanned so far no crash.

**Comment by ShyGuyMD** [comment]
Update:
Tried mining the Tile, dropping the item, and scanning the item entity. Works just fine when doing that.

**Comment by Mandabar** [comment]
Did you get the coords of what location? Was it the same one I scanned (and dissapeared across disco/reconnects)?

**Comment by ShyGuyMD** [comment]
Yes, it was the same.

**Comment by kwifrog** [comment]
I'll do some further testing an push magic pretty hard on this server update.

**Comment by ShyGuyMD** [comment]
Further testing shows that, if said Obsidian Tile has the sinister node spawned in it, it can be scanned just fine.

**Comment by tterrag1098** [comment]
I can almost see the error here, and it would be insanely easy to fix...if only TC was opensource. _sigh_

**Comment by ShyGuyMD** [comment]
Hack it >_>

I've already reported the bug to Azanor, maybe he'll push a quick bugfixing update, for some reason (?

**Comment by Mandabar** [comment]
Azanor. Quick bugfix update?

HAHAHAHAHAHAHAHAA

Hah.

Still waiting on some sort of fix/hack/workaround for biomes to actually spawn. Must be odd to never have magical forest/taint 1.7.10. Wonder how he never noticed that issue :P

**Comment by ShyGuyMD** [comment]
That's the joke 8D

**Comment by kwifrog** [comment]
This was apparently fixed in the newest Thaumcraft updates. We're currently trying to work out the newest Cauldron update to see if we can use it.

As it stands, we can't use the newest Thaumcraft because of a forge incompatibility in Cauldron.

**Comment by Mandabar** [comment]
Forge Compatibility thing resolved. Now Thaumcraft issue with being unable to disable taint/magical forest generation... on par with vanilla.. just as common as vanilla. And huge.
FailFish

**Comment by kwifrog** [comment]
This issue should have resolved in the Thaumcraft update. Feel free to reopen it if the issue persists
