### ISSUE TITLE
3x1 mode not working in the Nether

### ISSUE THREAD

**Issue by ShyGuyMD** [wyldmods/WyldCraftIssues#12]
Tried the 3x1 mode with the pickaxe on some Nether Quartz and it didn't work. Will try with other ores if I find a cluster.

Didn't text 3x3 because of no Emeralds.

**Comment by kwifrog** [comment]
3x1 is not meant to work on the floor, but it is being looked at.

Nether Quartz issue is a Nether Ores bug, but a work around is being written.
