### ISSUE TITLE
Infernal Furnace

### ISSUE THREAD

**Issue by ShyGuyMD** [wyldmods/WyldCraftIssues#14]
Infernal Furnaces are not taking in Ignis from nearby unlabeled Jars. Haven't tried labeled yet, but that should not be a problem.

**Comment by Mandabar** [comment]
Reread how thaumcraft now works, Things have changed. It has to be piped, or come from a vis relay. No more magic floating essentia.

Only infusion altar still works with floating essentia from jars.

**Comment by ShyGuyMD** [comment]
Well, I guess my page was outdated then. It still said it had to be within line of sight from the furnace xD
