### ISSUE TITLE
Breaking Leaves Instantly in Survival

### ISSUE THREAD

**Issue by kwifrog** [wyldmods/WyldCraftIssues#16]
Just putting this here for reference.

**Comment by tterrag1098** [comment]
yeah idunnolol

**Comment by tterrag1098** [comment]
http://ci.tterrag.com/job/EnderIO-RF/36/

**Comment by kwifrog** [comment]
AH HA!

**Comment by Mandabar** [comment]
#BlameGarrett then as usual? :D 
Love ya :heart_eyes:

**Comment by tterrag1098** [comment]
Nonono, CrazyPants made that change. I fixed it.

#ThankGarrett
