### ISSUE TITLE
Livestock won't breed

### ISSUE THREAD

**Issue by ConditionOfMan** [wyldmods/WyldCraftIssues#17]
Cows and sheep won't consume wheat or breed. When you right-click on them they get the heart particles, but they don't produce offspring. Pigs won't consume carrots or breed either, but will also get the heart particles.

**Comment by Mandabar** [comment]
Can only be bred from inside your claimed areas

**Comment by ConditionOfMan** [comment]
Gotcha. I'll try again when I expand my claim.

**Comment by Mandabar** [comment]
Should we change that breeding is limited to inside claims? Input folks?

**Comment by kwifrog** [comment]
I vote to change it personally. Seems a bit silly.

**Comment by MikeLydeamore** [comment]
I also vote to change it.

**Comment by ConditionOfMan** [comment]
I also vote for it to be changed :-)

**Comment by tterrag1098** [comment]
sounds unanimous to me.

**Comment by Mandabar** [comment]
As the masses wish! Will be implemented post haste.
