### ISSUE TITLE
Auto-refill bug

### ISSUE THREAD

**Issue by ConditionOfMan** [wyldmods/WyldCraftIssues#18]
When I open my inventory the next time after inventory tweaks auto-refilled a hotbar, the cursor will be holding an item that could have been selected as an auto-refill candidate. For example, if I have two hoes in my inventory and one in my hotbar, and the hotbar one breaks, a hoe will be placed in my hotbar. The next time I open my inventory, I will have one hoe in my hotbar and one hoe "picked up" in my cursor.

A work-around is to open inventory tweaks and turn off auto-refill.

**Comment by kwifrog** [comment]
It sounds like SOMEONE forgot to install InventoryTweaks on the server again... MANDABAR

**Comment by Mandabar** [comment]
It's there already. So wrong kiwi :P

http://puu.sh/bRWdl/0344c88823.png

**Comment by kwifrog** [comment]
Well then, regular old inventory tweaks on servers then. Not much else we can do.
