### ISSUE TITLE
I think I broke it again

### ISSUE THREAD

**Issue by RopeyPlague** [wyldmods/WyldCraftIssues#20]
So I set up a cursed earth farm in the nether with conveyor belts and the server closed on me. So there might be something up with conveyors being put in a certain way. They were feed off on to half slabs so that might be something.

**Comment by Mandabar** [comment]
The belts really don't like pushing items into something. So into a hopper at the same level is bad. Block below will probably be ok. Unsure on halfslabs below the same left. Above the same level would be bad as well I guess. 

Once again, two different crash logs. I started it and it seems to be working with no issues. Probably until someone loads that area again.
http://puu.sh/c5ZrI/e29aaf82ec.txt
http://puu.sh/c5Zto/f10dbe1429.txt

We may need to just disable these conveyor belts again on the server. I could do so via plugin. Probably not an issue on SSP. Possibly a Cauldron issue.I say this because it might not be an issue elsewhere, and we are releasing the pack publicly, not just for the server use.

**Comment by RopeyPlague** [comment]
yeah I think it just has a problem with the half slaps o.O . it was working fine when I had a block at the end of them. And my crystal essence farm works perfectly without any problems. So like you said. It could just be like hell no when its being pushing a item into a hopped or onto a half slab.

**Comment by Mandabar** [comment]
Welp. Can't enter the nether now...

**Comment by RopeyPlague** [comment]
:/ well that's where I'm at so I can't play for now XD. At least we are learning the conveyor's break the server now :)

**Comment by Mandabar** [comment]
Last few times it sorta fixed itself.. or doing a cofh killall item/s worked.. but I think the dim has to be loaded at the very least, w/o loading that chunk. Let me try something else

**Comment by Mandabar** [comment]
Well.. That didn't work. Well at the least, I can get you back in by delete/rename/backup your player data. Have to wait till someone smarter fixes it. Or it fixes itself.

Lose your items. Not your Thaumcraft knowledge :( I dunno another way of moving your spawn in point.

**Comment by RopeyPlague** [comment]
well that's not fun at all XD. I can't believe that keeps happening. I make something that simple and it breaks all the things. there was nothing complex about it like the first time :(

**Comment by Mandabar** [comment]
Its the belts. They just aren't happy pushing items into something. Take a look at the second crash log I posted.

**Comment by RopeyPlague** [comment]
Yeah I know. It seems to not cause problems if it's a block it's pushing something into. anything else it seems to freak out :/ . I had that going for a good 30 minutes or so. Then when I added a few more conveyor belts it just freaked.

**Comment by Mandabar** [comment]
I'm in server still trying to see if I can get it to load. deleted my data a few times, not that it matters :p
What did you add, going into what exactly?

Your last crash machine, I could use it for awhile. items moving about.. no crash. And then it does. Even crashed once with no items in the system. Just water. Water by itself. Yep. So it could be rng too. not really stable it seems. I wonder if this happens in ssp as well or not.

**Comment by RopeyPlague** [comment]
well I had a block with a half slab above it at the end of the conveyor belts. I was using a magnet to put the items out. then I replaced the blocks with conveyor belts to not have to use the magnet. That's when the server went down.

**Comment by Mandabar** [comment]
Hmm.. I see. Well we have it fixed in server. had to resort to MCEdit to fix it though.

**Comment by kwifrog** [comment]
We've disabled conveyors for now until we can locate the source of the issue.

**Comment by tecnobrat** [comment]
This has been fixed.
