### ISSUE TITLE
RF Oven Client Crash Bug

### ISSUE THREAD

**Issue by ConditionOfMan** [wyldmods/WyldCraftIssues#21]
Trying to shift-click wood into the KitchenCraft RF oven will will result in client crash.

**Comment by ConditionOfMan** [comment]
Tested with oak and birch wood, oak planks, fences, and carpenter's blocks. They all crashed the client. I suspect it's something to do with burnables (which have no place in the RF oven).

**Comment by kwifrog** [comment]
I think Garrett figured out it was a shift-click issue.

**Comment by tterrag1098** [comment]
Can I have the log?

**Comment by ConditionOfMan** [comment]
Here are several :-)

https://dl.dropboxusercontent.com/u/70120365/2014-10-12-1.log.gz
https://dl.dropboxusercontent.com/u/70120365/2014-10-12-2.log.gz
https://dl.dropboxusercontent.com/u/70120365/2014-10-12-3.log.gz
https://dl.dropboxusercontent.com/u/70120365/2014-10-12-4.log.gz
https://dl.dropboxusercontent.com/u/70120365/2014-10-12-5.log.gz
https://dl.dropboxusercontent.com/u/70120365/2014-10-12-6.log.gz
https://dl.dropboxusercontent.com/u/70120365/2014-10-12-7.log.gz
