### ISSUE TITLE
Free hats!

### ISSUE THREAD

**Issue by Shadeyr** [wyldmods/WyldCraftIssues#22]
Not that i have a problem with it, but i got a hats because mobs like zombies and skeletons were burning in daylight.

**Comment by Mandabar** [comment]
Hats are based on time spent in game, not on kills in our configuration.
You get one every fifteen minutes playing or so. Slightly longer each time.

**Comment by kwifrog** [comment]
Yep, Mandabar is correct. Closing this now.
