### ISSUE TITLE
Cooked Porkchop

### ISSUE THREAD

**Issue by CrackerJac** [wyldmods/WyldCraftIssues#23]
The Cooked Pork Chop is backwards from the raw it will poison you cooked and raw will not.

**Comment by kwifrog** [comment]
Seems like Garrett left in his test item for KitchenCraft food modifications. #BlameTterrag

**Comment by CrackerJac** [comment]
Cool just putting it out there

**Comment by tterrag1098** [comment]
Fixed in above commit (if you can even see that? kiwi can)
