### ISSUE TITLE
Hat mod

### ISSUE THREAD

**Issue by CrackerJac** [wyldmods/WyldCraftIssues#24]
Don't know if its just my minecraft but hats are taking longer to show what you got in the corner of the screen.

**Comment by kwifrog** [comment]
I'm not sure what you mean.

You gain hats by playing. First one is 15 minutes, next one is 15 + n% (I can't remember the percentage increase right now.

**Comment by CrackerJac** [comment]
so by killing the animal that has the hat it does not pop up in the corner saying you just got the hat but after 15 mins it will. Is that right

**Comment by tterrag1098** [comment]
No. Hats you get are random. Killing mobs with hats does nothing.

**Comment by CrackerJac** [comment]
oh ok i see so it doesn't matter if it has a hat. Its all RNG
