### ISSUE TITLE
Random Things: Obsidian stick crafting broken.

### ISSUE THREAD

**Issue by KiroNZ** [wyldmods/WyldCraftIssues#25]
Random Things: Obsidian stick (ID: 4475:1) is crafting broken. Because it has the same recipe as Obsidian stick (ID: 4621) from WR-CBE Core. This directly affects the crafting of Spectre Sword (ID: 4468) from Random things. Suggest adding either Ore dict compat or Minetweaker recipe over-ride.

**Comment by Mandabar** [comment]
I thought we did already... kiwi will need to recheck

**Comment by KiroNZ** [comment]
Using v1.0.1 (current)

**Comment by kwifrog** [comment]
I had taken this into account. The stick from WR-CBE was removed completely and their recipes were altered.

I'll check what's wrong in the ATL version in the morning.

**Comment by kwifrog** [comment]
Ok, Everything checks out on the ATL version. I suggest you reinstall the pack and get back to us.

The WR-CBE obsidian stick doesn't have a recipe anymore. And it doesn't show up in NEI.

**Comment by KiroNZ** [comment]
Confirmed it works fine when run from the AT Launcher. (I always put it in MultiMC for several reasons, and err, _someone_ forgot the scripts folder). You can go ahead and close this issue.

**Comment by kwifrog** [comment]
Hah. Glad to hear it's fixed for you :P
