### ISSUE TITLE
game suddenly closes

### ISSUE THREAD

**Issue by pistonpusher** [wyldmods/WyldCraftIssues#26]
nothing much else to say, the game suddenly closes and I'm sitting there looking at the ATLauncher console.   http://paste.atlauncher.com/view/776c13c4

this has happened several times, this is the latest log

**Comment by MikeLydeamore** [comment]
ExceptionAccessViolation is usually an issue with your java install. Have you experienced this with any other packs?

**Comment by pistonpusher** [comment]
no, this is the only pack it has happened on, otherwise I would not have reported it, but I will reinstall java to see if it stops happening.  thanks for the prompt reply.

**Comment by pistonpusher** [comment]
here's another, just happened  
http://paste.atlauncher.com/view/0065aa08

**Comment by tterrag1098** [comment]
Hum, your jvm is crashing, not the game. Can't really say what's going on there.

**Comment by pistonpusher** [comment]
Thanks
