### ISSUE TITLE
veinmine enchant doesn't work on destruction pick

### ISSUE THREAD

**Issue by mrclyde** [wyldmods/WyldCraftIssues#35]
it is possible to enchant destruction pick and get veinmine enchant, or do it in anvil, however the enchant does not actually work on this pick.

**Comment by kwifrog** [comment]
I'll have to add it to the blacklist. I don't think VeinMiner would really work with the way the Destruction Pick is coded..

**Comment by MikeLydeamore** [comment]
It indeed will not work, as the destruction pickaxe doesn't work on any ores.

**Comment by mrclyde** [comment]
@kiwi Nope it does not work in other packs, where veinmine is standard either. Just thought that when it is possible to put the enchant on in this pack that there was workaround. So it is totally fine to blacklist it.

@mike the point is not to veimine ores, but smoothstone, at the stage when you get veinmine book via enderio table you would really use veinmine enchant only for cleaning up space underground / removing old bases, not mining ores.

**Comment by kwifrog** [comment]
Yea, not being able to use it on smooth stone was intentional. But it's being added to the blacklist :P
