### ISSUE TITLE
Lumium blend doesn't craft

### ISSUE THREAD

**Issue by Divided** [wyldmods/WyldCraftIssues#36]
Got all the mats, tried with both pulverized tin and silver, along with the bucket of energized glowstone.
Shift click from NEI does nothing, placing the items manually in the crafting window gives no result.

**Comment by kwifrog** [comment]
The recipe is 3 pulverized tin, 1 pulverized silver, and one bucket of Energized Glowstone. I've made it just fine in testing.

Shift-clicking won't work with non-stackable items.

**Comment by Divided** [comment]
You are right, it works with the proper mix, my bad!
