### ISSUE TITLE
Farm Station not pulling KitchenCraft mod food & seeds

### ISSUE THREAD

**Issue by Digi7alFox** [wyldmods/WyldCraftIssues#37]
The farming stations  are not pulling any of the KitchenCraft mod foods or seeds back into the machine.  I can place the seeds into the farming station and the station will plant the seeds but when the plant is fully grown the plant will break apart but the station will not pick up the seeds or the food.

**Comment by ghost** [comment]
Can confirm. EnderIO farming stations are not picking up Kitchencraft produce and seeds.

**Comment by ElvenDeity** [comment]
Kitchencraft does work with farming station (currently got 6 farming station up with all the kitchen craft items). I do believe it was fixed recently (as i've only tryed it after the newest release)..

**Comment by tterrag1098** [comment]
Yeah this was fixed in the last update to KC and thus wyldcraft.
