### ISSUE TITLE
Villager Trades

### ISSUE THREAD

**Issue by ShyGuyMD** [wyldmods/WyldCraftIssues#4]
Are villager trades supposed to be off?

Came across a village and none of the villagers would even display the trading UI. Will try with a Trading Post, once I get resources, otherwise.

**Comment by Mandabar** [comment]
It was a default plugin setting. will be changed soon to allow trades in wilderness. Was set to be allowed at your claim only by default -__-

**Comment by tterrag1098** [comment]
Gotta love them plugins :D
