### ISSUE TITLE
Tesseract and Capacitor Bank(basic)

### ISSUE THREAD

**Issue by Hillkoz** [wyldmods/WyldCraftIssues#45]
Hi everyone,

I tried to put a tesseract from my nether factory to send energy to the overworld.
But when I tried to connect it on my capacitor bank, the capacitor bank do not accept the tesseract as an input. I tried to had an energy conduit between them but no energy come in my capacitor bank.

My only way to make it work is to send lava and have my lava generator connected to the capacitor bank.

**Comment by tterrag1098** [comment]
Put the tesserract on send/receive and it should be allowed to pull. If that fails just put a conduit in between.

**Comment by Hillkoz** [comment]
My english is not very good(Frenchy). I think you didn't understand what I want to say(or I just mess up).

I have tried with and without ender energy conduit between the lava generator and the tesseract and with and without ender energy conduit between the capacitor bank and the tesseract, but no energy received.

In the Nether, I did a lava production and plug it on a lava generator(x64) connected to a tesseract in  send energy mode.
In the overworld I tried both with and without conduit to receive energy.
When I put the tesseract in contact with the bank, the bank refuse to put the I/O, where the tesseract is, on pull mode(only push or disable).
When I used energy conduit between the tesseract and the bank, everything seems to be ok(I/O related) but, there is no energy reaching the bank.
I hope to have been more precise this time.

One thing I forgot, I'm playing on Sky Factory 2.

**Comment by Mandabar** [comment]
What tesseract? We don't have thermal expansion. If you mean the
dimensional transceiver from EnderIO  that's different.

First make sure both sides are chunk loaded. Second make sure it's sending
power in a sending power channel. And third the other side is receiving the
same channel on the receive power channel.

Transceivers have multiple input/output for all the sending/receiving
types. Items/power/fluid/EnderRail

Let me know if you get it working?

**Comment by Hillkoz** [comment]
Wait... Do I am in the Sky Factory 2 issues report?
Because in SF2, there is Thermal Expansion!
Or I have a wrong version?
There is actually Tesseract, dynamo, strongbox, pulverizer, etc... in my version of SF2!
I'm feeling lost...

**Comment by Mandabar** [comment]
This is wyldcraft issues, not skyfactory 2.

**Comment by Hillkoz** [comment]
Oups sorry for that!
