### ISSUE TITLE
Broken Node Textures

### ISSUE THREAD

**Issue by Raven2505** [wyldmods/WyldCraftIssues#5]
Floating nodes are just floating squares (broken texture)

**Comment by Mandabar** [comment]
For Thaumcraft? That's odd, they worked for me

**Comment by ShyGuyMD** [comment]
They show just fine for me.

**Comment by Raven2505** [comment]
I saw it at one of the chests inside the obsidian pillers ruin from thaumcraft

**Comment by Raven2505** [comment]
I will post image if I see it again.

**Comment by Raven2505** [comment]
I think it was something on my end to do with not enough memory... Feel free to close this issue.
