### ISSUE TITLE
No Texture for GhostWood Leaves

### ISSUE THREAD

**Issue by Raven2505** [wyldmods/WyldCraftIssues#8]
Ghostwood Leaves are invisable in menu and in hand. 

Also WAILA says they are called block.leaves..name

Also placing ghostwood leave are invisible and you can x-ray through the world

**Comment by kwifrog** [comment]
I'll have a look. Since you're having texture issues, I would redownload and reinstall the pack.

**Comment by ShyGuyMD** [comment]
Confirmed on NEI. Didn't come across any trees yet, so I don't know about in the x-ray thingie.

**Comment by MikeLydeamore** [comment]
Texture is indeed invisible, but they do not x-ray through the world. Little we can really do about that, but I will keep this open just in case.

**Comment by MikeLydeamore** [comment]
OK, they x-ray if graphics settings are on Fast.

Thank you for the report.

**Comment by kwifrog** [comment]
This has been reported to the mod author. We have disabled Ghostwood Trees.
