### ISSUE TITLE
Can't place water in the world.

### ISSUE THREAD

**Issue by ShyGuyMD** [wyldmods/WyldCraftIssues#9]
If you try to place a bucket of water in any place that's not already a water source block, it rollbacks to your hand. Intended?

**Comment by tterrag1098** [comment]
Water can only be placed in your plot...for now. I believe this is set to be changed. @Mandabar?

**Comment by Mandabar** [comment]
Also a default intended mechanic, to prevent mass griefing of wilderness. Will be disabled soon. Thanks Shy!
